spring:
  application:
    name: ecs-eureka
server:
  port: 8761
eureka:
  instance:
    hostname: ecs-eureka
  client:
    service-url:
      defaultZone: http://172.16.9.142:${server.port}/eureka
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false
#---
#spring:
#  profiles: eureka2
#server:
#  port: 8802
#eureka:
#  instance:
#    hostname: eureka2Z
#  client:
#    service-url:
#      defaultZone: http://localhost:8801/eureka