server:
  port: 8080

spring:
  rabbitmq:
    host: 172.16.1.175
    port: 5672
    username: wangjian
    password: 1234qwer
  mvc:
    view:
      prefix: /
      suffix: .jsp
#    publisher-confirms: true
#    virtual-host: /
#logging:
#  config: classpath:log4j.properties
