server:
  port: 8085

spring:
  application:
    name: ecs-oauthcenter
  # 配置 redis
  redis:
    # redis 数据库索引（默认为0）
    database: 0
    # redis 服务地址
    host: 172.16.1.175
    # redis 连接端口
    port: 6379
    # redis 服务器链接密码 （默认为空）
    password: 1234qwer
    # 连接超时时间 （毫秒）
    timeout: 5000
    # 配置 redis 连接池
    jedis:
      pool:
        # 连接池最大连接数　（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池的最大空闲连接
        max-idle: 8
        # 连接池中 最小空闲连接
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://172.16.9.175:8761/eureka/
