spring:
#  cloud:
#    config:
#      label: master
#      profile: dev
#      discovery:
#        enabled: true
#        service-id: cloud-config
  application:
    name: ecs-order
  profiles:
    active: dev

#  rabbitmq:
#    host: apg-server
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://172.16.9.175:8761/eureka/
  instance:
    prefer-ip-address: true


mybatis-plus:
  mapper-locations: classpath:/mapper/**Mapper.xml
  type-aliases-package: com.wangshi.order.entity
  global-config:
    db-config:
      id-type: uuid
      db-type: mysql
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
